# -*- coding: utf-8 -*-
"""問題2-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwcAHJlLwDpZRJEOFL1gE0UwZf-fEWtg
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
import matplotlib.pyplot as plt
import math

# 画像パス（自身の環境に合わせて確認）
image_path = '/content/drive/MyDrive/img2025/image/a2-3_binary_image.png'

# 画像読み込み
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# 3から13まで、2ずつ増やしてリストを作る（3, 5, 7, 9, 11, 13）
# 終了値を大きくすれば、もっと試せる（例: range(3, 21, 2)）
kernel_sizes = list(range(3, 17, 2))

# 画像の総数（オリジナル + 処理結果の数）
total_images = 1 + len(kernel_sizes)

# レイアウト設定
cols = 4  # 1行に並べる数
rows = math.ceil(total_images / cols) # 必要な行数を自動計算

plt.figure(figsize=(15, 4 * rows))

# 1. オリジナル画像を表示
plt.subplot(rows, cols, 1)
plt.title('Original')
plt.imshow(img, cmap='gray')
plt.axis('off')

# 2. ループ処理でサイズを変えながら表示
for i in range(len(kernel_sizes)):
    k = kernel_sizes[i]

    # カーネル作成と処理
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (k, k))
    result = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

    # 結果を表示（場所は i + 2 番目）
    plt.subplot(rows, cols, i + 2)
    plt.title(f'Kernel Size: {k}')
    plt.imshow(result, cmap='gray')
    plt.axis('off')

plt.tight_layout()
plt.show()