# -*- coding: utf-8 -*-
"""問題2-2#2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1La6z4iK8IV6PEYigjfX3vHFJ6G3TQe3m
"""

# ドライブのマウント
from google.colab import drive
drive.mount('/content/drive')

# モジュールのインポート
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from skimage.metrics import structural_similarity as ssim # SSIM計算用

# 共通のディレクトリパス
common_path = '/content/drive/MyDrive/img2025/image/'
filename = 'a2-4_color_image.png' # 課題指定のファイル名

# 画像を読み込む
original_img = cv2.imread(common_path + filename)

# 画像が正しく読み込めているか確認（読み込めない場合はNoneになるためエラー回避）
if original_img is None:
    print(f"Error: {filename} が見つかりません。パスを確認してください。")
else:
    # 元画像のファイルサイズを取得 (バイト単位)
    original_size = os.path.getsize(common_path + filename)
    print(f"元画像読み込み完了: {filename}, サイズ: {original_size/1024:.2f} KB")

# 結果を格納するリスト
qualities = []
file_sizes = []
compression_ratios = []
ssim_scores = []

# 画像表示の準備 (3行4列のグリッドで表示)
plt.figure(figsize=(20, 15))

# 元画像をRGB変換（SSIM計算と表示用）
original_img_rgb = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)

# 0から100まで10刻みでループ
for i, quality in enumerate(range(0, 101, 10)):
    # 1. JPEG圧縮保存
    output_filename = f'compressed_{quality}.jpg'
    output_path = common_path + output_filename

    # 第2引数でJPEG品質を指定
    cv2.imwrite(output_path, original_img, [int(cv2.IMWRITE_JPEG_QUALITY), quality])

    # 2. 圧縮後のファイルサイズ取得
    comp_size = os.path.getsize(output_path)
    comp_ratio = (comp_size / original_size) * 100 # 元画像に対するサイズ比率(%)

    # 3. 圧縮画像の読み込みとRGB変換
    compressed_img = cv2.imread(output_path)
    compressed_img_rgb = cv2.cvtColor(compressed_img, cv2.COLOR_BGR2RGB)

    # 4. SSIM (画質評価値) の計算
    # channel_axis=2 はカラー画像(マルチチャンネル)であることを指定
    score = ssim(original_img_rgb, compressed_img_rgb, win_size=3, channel_axis=2, data_range=255)

    # リストにデータを保存
    qualities.append(quality)
    file_sizes.append(comp_size)
    compression_ratios.append(comp_ratio)
    ssim_scores.append(score)

    # 5. サブプロットへの表示
    plt.subplot(3, 4, i + 1)
    plt.imshow(compressed_img_rgb)
    plt.title(f"Q={quality}\nSize: {comp_ratio:.1f}%, SSIM: {score:.3f}")
    plt.axis('off')

# レイアウト調整と表示
plt.tight_layout()
plt.show()