# -*- coding: utf-8 -*-
"""問題2-3-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwZO9eY3hMiF-v-SEBzxZ-4SCiz3TaxX
"""

# ドライブのマウント
from google.colab import drive
drive.mount('/content/drive')

# モジュールのインポート
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 共通のディレクトリパス
common_path = '/content/drive/MyDrive/img2025/image/'

# 画像を読み込む
filename = 'a2-5_gray_image.png'
gray_img = cv2.imread(common_path + filename, cv2.IMREAD_GRAYSCALE)

# 画像を正方形（512x512）にトリミングする処理
# 画像の中心から指定サイズを切り出す
h, w = gray_img.shape
crop_size = 512

# 画像サイズがトリミングサイズより小さい場合の例外処理（念のため）
if h < crop_size or w < crop_size:
    print(f"画像サイズが小さいため、トリミングサイズを調整します: {min(h, w)}")
    crop_size = min(h, w)

center_y, center_x = h // 2, w // 2
start_x = center_x - crop_size // 2
start_y = center_y - crop_size // 2
cropped_img = gray_img[start_y:start_y+crop_size, start_x:start_x+crop_size]

# 2次元高速フーリエ変換（2D-FFT）
fourier = np.fft.fft2(cropped_img)

# ゼロ周波数成分（直流成分）を画像の中心にシフトする
fshift = np.fft.fftshift(fourier)

# 振幅スペクトルを計算する
amp_spectrum = np.abs(fshift)

# 対数スケールに変換（見やすくするため +1 して log をとる）
log_amp_spectrum = 20 * np.log10(amp_spectrum + 1)

# 実行結果の表示
plt.figure(figsize=(10, 5))

# トリミング後の元画像
plt.subplot(1, 2, 1)
plt.title('Cropped Image (512x512)')
plt.imshow(cropped_img, cmap='gray', vmin=0, vmax=255)
plt.axis('off')

# 振幅スペクトル（対数スケール・中心化済み）
plt.subplot(1, 2, 2)
plt.title('Magnitude Spectrum (Log Scale)')
plt.imshow(log_amp_spectrum, cmap='gray')
plt.axis('off')

plt.tight_layout()
plt.show()