# -*- coding: utf-8 -*-
"""問題2-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14oortqIl9hjtngj_clywKmLNDSRRMBjh
"""

# ==========================================
# 課題4: 2種類以上の周波数フィルタの適用と考察
# ==========================================
# 1. 準備と画像読み込み
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive

# ドライブのマウント
drive.mount('/content/drive')

# パスとファイル名の設定
common_path = '/content/drive/MyDrive/img2025/image/'
filename = 'a2-5_gray_image.png'

# 画像読み込み
gray_img = cv2.imread(common_path + filename, cv2.IMREAD_GRAYSCALE)

# 画像の正方形トリミング（課題3の処理を継承）
h, w = gray_img.shape
crop_size = 512
target_size = min(h, w, crop_size)

center_y, center_x = h // 2, w // 2
start_y = center_y - target_size // 2
start_x = center_x - target_size // 2
img = gray_img[start_y:start_y+target_size, start_x:start_x+target_size]

print(f"画像読み込み完了: {img.shape}")

# 2. FFT実行とフィルタ関数の定義・適用

# --- FFTの実行 ---
f = np.fft.fft2(img)
fshift = np.fft.fftshift(f) # 直流成分を中心に移動

# --- フィルタ生成関数の定義 ---
def create_ideal_lowpass(shape, cutoff):
    """理想ローパスフィルタ"""
    rows, cols = shape
    crow, ccol = rows // 2, cols // 2
    y, x = np.ogrid[:rows, :cols]
    dist_sq = (x - ccol)**2 + (y - crow)**2
    mask = np.zeros(shape)
    mask[dist_sq <= cutoff**2] = 1
    return mask

def create_gaussian_highpass(shape, cutoff):
    """ガウシアンハイパスフィルタ"""
    rows, cols = shape
    crow, ccol = rows // 2, cols // 2
    y, x = np.ogrid[:rows, :cols]
    dist_sq = (x - ccol)**2 + (y - crow)**2
    # ガウシアンローパスの逆（1から引く）
    mask = 1 - np.exp(-dist_sq / (2 * (cutoff**2)))
    return mask

# --- パラメータ設定と適用 ---
D0_low = 30   # ローパス用遮断周波数
D0_high = 30  # ハイパス用遮断周波数

# マスク作成とフィルタリング
mask_ilpf = create_ideal_lowpass(img.shape, D0_low)
mask_ghpf = create_gaussian_highpass(img.shape, D0_high)

fshift_ilpf = fshift * mask_ilpf
fshift_ghpf = fshift * mask_ghpf

# 逆FFT処理
img_ilpf = np.fft.ifft2(np.fft.ifftshift(fshift_ilpf)).real
img_ghpf = np.fft.ifft2(np.fft.ifftshift(fshift_ghpf)).real

print("フィルタ処理完了")

# 3. 結果の可視化
plt.figure(figsize=(12, 8))

# --- 上段: 理想ローパスフィルタ ---
plt.subplot(2, 3, 1)
plt.title('Original Image')
plt.imshow(img, cmap='gray', vmin=0, vmax=255)
plt.axis('off')

plt.subplot(2, 3, 2)
plt.title(f'Ideal Low Pass Filter Mask\n(Cutoff={D0_low})')
plt.imshow(mask_ilpf, cmap='gray', vmin=0, vmax=1)
plt.axis('off')

plt.subplot(2, 3, 3)
plt.title('Filtered Result (ILPF)')
plt.imshow(img_ilpf, cmap='gray')
plt.axis('off')

# --- 下段: ガウシアンハイパスフィルタ ---
plt.subplot(2, 3, 4)
plt.title('Original Image')
plt.imshow(img, cmap='gray', vmin=0, vmax=255)
plt.axis('off')

plt.subplot(2, 3, 5)
plt.title(f'Gaussian High Pass Filter Mask\n(Cutoff={D0_high})')
plt.imshow(mask_ghpf, cmap='gray', vmin=0, vmax=1)
plt.axis('off')

plt.subplot(2, 3, 6)
plt.title('Filtered Result (GHPF)')
plt.imshow(np.abs(img_ghpf), cmap='gray') # 振幅を表示
plt.axis('off')

plt.tight_layout()
plt.show()